[General]
initialize_flag=1
o44atsi7sb2cujzzyxnh3q%40xmpp.zoom.us.asyn.enc.db=1
o44atsi7sb2cujzzyxnh3q%40xmpp.zoom.us.enc.db=1
o44atsi7sb2cujzzyxnh3q%40xmpp.zoom.us.idx.enc.db=1
o44atsi7sb2cujzzyxnh3q%40xmpp.zoom.us.sync.enc.db=1
random_key="iQswYAEmghp9EbazC67zKHYwSMbSDZbtQbAHOT0glio="
